---
abstract: 'a collection of PoCos useful for Web Development'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Data::Dumper: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  lib: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Bundle-WebDevelopment
provides:
  POE::Component::App::PNGCrush:
    file: lib/POE/Component/App/PNGCrush.pm
    version: 1.001003
  POE::Component::Bundle::WebDevelopment:
    file: lib/POE/Component/Bundle/WebDevelopment.pm
    version: 1.001003
  POE::Component::CSS::Minifier:
    file: lib/POE/Component/CSS/Minifier.pm
    version: 1.001003
  POE::Component::JavaScript::Minifier:
    file: lib/POE/Component/JavaScript/Minifier.pm
    version: 1.001003
  POE::Component::Syntax::Highlight::CSS:
    file: lib/POE/Component/Syntax/Highlight/CSS.pm
    version: 1.001003
  POE::Component::Syntax::Highlight::HTML:
    file: lib/POE/Component/Syntax/Highlight/HTML.pm
    version: 1.001003
  POE::Component::WWW::Alexa::TrafficRank:
    file: lib/POE/Component/WWW/Alexa/TrafficRank.pm
    version: 1.001003
  POE::Component::WWW::Cache::Google:
    file: lib/POE/Component/WWW/Cache/Google.pm
    version: 1.001003
  POE::Component::WWW::DoctypeGrabber:
    file: lib/POE/Component/WWW/DoctypeGrabber.pm
    version: 1.001003
  POE::Component::WWW::GetPageTitle:
    file: lib/POE/Component/WWW/GetPageTitle.pm
    version: 1.001003
  POE::Component::WWW::Google::PageRank:
    file: lib/POE/Component/WWW/Google/PageRank.pm
    version: 1.001003
  POE::Component::WWW::HTMLTagAttributeCounter:
    file: lib/POE/Component/WWW/HTMLTagAttributeCounter.pm
    version: 1.001003
  POE::Component::WWW::Lipsum:
    file: lib/POE/Component/WWW/Lipsum.pm
    version: 1.001003
  POE::Component::WWW::WebDevout::BrowserSupportInfo:
    file: lib/POE/Component/WWW/WebDevout/BrowserSupportInfo.pm
    version: 1.001003
  POE::Component::WebService::HtmlKitCom::FavIconFromImage:
    file: lib/POE/Component/WebService/HtmlKitCom/FavIconFromImage.pm
    version: 1.001003
  POE::Component::WebService::Validator::CSS::W3C:
    file: lib/POE/Component/WebService/Validator/CSS/W3C.pm
    version: 1.001003
  POE::Component::WebService::Validator::HTML::W3C:
    file: lib/POE/Component/WebService/Validator/HTML/W3C.pm
    version: 1.001003
requires:
  App::PNGCrush: 0
  CSS::Minifier: 0
  Carp: 0
  JavaScript::Minifier: 1.10
  LWP::UserAgent: 0
  POE: 0
  POE::Component::NonBlockingWrapper::Base: 0
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  Syntax::Highlight::CSS: 0
  Syntax::Highlight::HTML: 0
  URI: 0
  WWW::Alexa::TrafficRank: 0
  WWW::Cache::Google: 0
  WWW::DoctypeGrabber: 0
  WWW::GetPageTitle: 0
  WWW::Google::PageRank: 0
  WWW::HTMLTagAttributeCounter: 0
  WWW::Lipsum: 0
  WWW::WebDevout::BrowserSupportInfo: 0
  WebService::HtmlKitCom::FavIconFromImage: 0
  WebService::Validator::CSS::W3C: 0
  WebService::Validator::HTML::W3C: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/poe-component-bundle-webdevelopment/issues
  homepage: http://metacpan.org/release/POE-Component-Bundle-WebDevelopment
  repository: git://github.com/zoffixznet/poe-component-bundle-webdevelopment.git
version: 1.001003
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::ZOFFIX/OurPkgVersion'
      version: 0.005001
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 1
          modules: []
          phase: release
          skip:
            - strict
            - warnings
            - base
            - ExtUtils::MakeMaker
            - IPC::Open3
            - File::Copy
      name: '@Author::ZOFFIX/PromptIfStale'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::ZOFFIX/GatherDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ZOFFIX/PruneCruft'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ZOFFIX/ManifestSkip'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ZOFFIX/MetaYAML'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ZOFFIX/License'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ZOFFIX/Readme'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ZOFFIX/ExecDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ZOFFIX/ShareDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::ZOFFIX/MakeMaker'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ZOFFIX/Manifest'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ZOFFIX/AutoPrereqs'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ZOFFIX/MetaConfig'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::ZOFFIX/Prereqs::AuthorDeps'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ZOFFIX/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: 5.012
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::ZOFFIX/MetaProvides::Package'
      version: 2.000000
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::ZOFFIX/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ZOFFIX/InstallGuide'
      version: 1.200002
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::ZOFFIX/ReadmeAnyFromPod'
      version: 0.133360
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::ZOFFIX/Test::Compile'
      version: 2.039
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::ZOFFIX/Test::DistManifest'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::ZOFFIX/Test::EOL'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ZOFFIX/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee::Extra
      name: '@Author::ZOFFIX/Test::Kwalitee::Extra'
      version: v0.2.0
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ZOFFIX/MetaTests'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::ZOFFIX/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::ZOFFIX/MojibakeTests'
      version: 0.5
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::ZOFFIX/NoTabsTests'
      version: 0.06
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ZOFFIX/PodSyntaxTests'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::ZOFFIX/Test::Portability'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::ZOFFIX/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::ZOFFIX/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
      name: '@Author::ZOFFIX/CheckSelfDependency'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ZOFFIX/CheckPrereqsIndexed'
      version: 0.010
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ZOFFIX/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ZOFFIX/AutoMetaResources'
      version: 1.20
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      name: '@Author::ZOFFIX/CopyFilesFromRelease'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ZOFFIX/TestRelease'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ZOFFIX/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ZOFFIX/ConfirmRelease'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::ZOFFIX/Git::Check'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::ZOFFIX/Git::Commit'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::ZOFFIX/Git::Tag'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::ZOFFIX/Git::Push'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ZOFFIX/UploadToCPAN'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Encoding
      name: Encoding
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.012
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.012
